---
- name: Get Wowza
  get_url: url=http://www.wowza.com/downloads/WowzaStreamingEngine-4-1-2/{{ wowza_version }} dest=/home/vagrant/{{ wowza_version }} mode=0755
- name: install expect
  apt: name={{ item }} update_cache=yes
  with_items: the_expectables
- name: push expect templates
  template: src=script.exp.j2 dest=/home/vagrant/script.exp mode=0755
- name: Run expect script, which runs Wowza installer
  args:
    creates: /usr/local/WowzaStreamingEngine/conf/Server.license
  shell: ./script.exp
