---
- name: Get Wowza
  get_url: url=https://www.wowza.com/downloads/{{ wowza_package }}/{{ wowza_version }}-linux-x64-installer.run dest=/tmp/{{ wowza_version }}-linux-x64-installer.run mode=0755
- name: install expect
  apt: name=expect update_cache=yes
- name: push expect templates
  template: src=script.exp.j2 dest=/tmp/script.exp mode=0755
- name: Run expect script, which runs Wowza installer
  args:
    creates: /usr/local/WowzaStreamingEngine/conf/Server.license
  shell: /tmp/script.exp

- name: WowzaStreamingEngine service started and enabled
  service: name=WowzaStreamingEngine state=started enabled=yes
